# permissions for end users to edit metadata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: metadata-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: leo-operator
    app.kubernetes.io/part-of: leo-operator
    app.kubernetes.io/managed-by: kustomize
  name: metadata-editor-role
rules:
- apiGroups:
  - foundations.le0exxx
  resources:
  - metadata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - foundations.le0exxx
  resources:
  - metadata/status
  verbs:
  - get
