---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - foundations.le0exxx
  resources:
  - metadata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - foundations.le0exxx
  resources:
  - metadata/finalizers
  verbs:
  - update
- apiGroups:
  - foundations.le0exxx
  resources:
  - metadata/status
  verbs:
  - get
  - patch
  - update
